fdefaults:
  - cfg

name: ldm_sf
resume_pretrained: 
ldm: true
depth_channels: 4
divis_by: 8
prediction_space: disp
camera_resolution: 320x240 #  WxH
image_size: [240,320] # H,W
train_dataset: [ClearPose, Dreds, HssdIsaacStd] # [Dreds] #
eval_dataset: [ClearPose, Dreds, HssdIsaacStd] # [Dreds] #
dataset_weight: [1, 1, 1] # [1] #
train_batch_size: 16
gradient_accumulation_steps: 1
eval_num_batch: -1
eval_batch_size: 4
lr_warmup_steps: 5000
learning_rate: 3e-5
lr_scheduler: constant # linear: almost the same as constant
val_every_global_steps: 1000
save_model_epochs: 3
num_train_timesteps: 1000
num_inference_timesteps: 10
num_intermediate_images: 5
num_inference_rounds: 1
ssi: false
normalize_mode: average
num_chs: 1
ch_bounds: [64.0]
ch_gammas: [1.]
noise_strategy: randn
loss_type: mse
prediction_type: v_prediction
sampler: ddpm
num_epochs: 200
cond_channels: rgb+raw
beta_schedule: scaled_linear
beta_start: 0.00085
beta_end: 0.012
mixed_precision: "no"
thresholding: false 
clip_sample: false
block_out_channels: [0] # N/A
